#!/bin/sh
# Build the local .tar.gz file from localhost.  The tar command is
# currently using too many
# work on this more later.

#########################################################################
### Configuration #######################################################
#########################################################################

PACKAGE="rgang"
VERSION=`grep Version: ../*spec | awk '{print $2}'`

(cd ../bin; test -L rgang || ln -s rgang.py rgang )

#########################################################################
### main () #############################################################
#########################################################################

tar --exclude '.git' --exclude '*.tar.gz' --exclude '*.sw*' \
    --exclude '.*ignore' --exclude '.tar' --exclude '*.list' \
    --exclude '*~' --exclude 'test_*' --exclude CVS \
    --exclude '__pycache__' --exclude 'cvs*' --exclude 'ups' \
    -czpf ../${PACKAGE}-${VERSION}.tar.gz ../*
